on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup dotnet
        uses: actions/checkout@v3
        with:
          dotnet-version: "6.x"
      - name: install dependencies
        run: dotnet restore
      - name: build application
        run: dotnet build
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{AZURE_CREDENTIALS}}
      - name: publish function
        uses: Azure/functions-action@v1.4.7
        with:
          app-name: PainGeneratorFunction20220819233849
          
